### ISSUE TITLE
南望山通信专业转码选手报到

### ISSUE THREAD

**Issue by BigCJL** [mxy493/CUGCS#2]
卧槽找到一个野生校友 握手。

**Comment by BigCJL** [comment]
老哥是在校生吗 多整点计院的资料 让我非科班的也来卷一卷

**Comment by mxy493** [comment]
> 老哥是在校生吗 多整点计院的资料 让我非科班的也来卷一卷

已经本科毕业了，有的资料都在这儿了🤝

**Comment by Siziyou** [comment]
老哥，你的仓库不知道什么原因挂掉了😥😥😥

**Comment by mxy493** [comment]
@Siziyou 应该一切正常哈，排查一下自己网络问题
