### ISSUE TITLE
请问有c语言的相关资料吗？

### ISSUE THREAD

**Issue by zengchen233** [mxy493/CUGCS#3]
你好！
    请问一下你有c语言相关的资料吗，中国地质大学考研专业课830是c语言和数据结构，c相关的资料在仓库中并没有找到😭，请问如果您有的话可以更新一下吗！谢谢！
@mxy493 @azeng233

**Comment by mxy493** [comment]
> 你好！ 请问一下你有c语言相关的资料吗，中国地质大学考研专业课830是c语言和数据结构，c相关的资料在仓库中并没有找到😭，请问如果您有的话可以更新一下吗！谢谢！ @mxy493 @azeng233

抱歉没有哈，我这里有的只是我自己积累下来的资料，我们专业也没有C语言的课！

**Comment by zengchen233** [comment]
好吧，还是谢谢你。
